### ISSUE TITLE
Does this work with todo comments with assignees?

### ISSUE THREAD

**Issue by cseas** [aki77/expiring-todo-comments-action#128]
The eslint unicorn plugin allows also specifying an assignee to the todos.
Is this action able to parse those todo comments too?

Examples:

```
// TODO @cseas [2019-11-15]: Refactor this code before the sprint ends.
// Todo: @cseas [2019-11-15]: Refactor this code before the sprint ends.
```

**Comment by aki77** [comment]
Currently, this pattern of TODO comments is not supported. 
However, we plan to review and enhance the functionality to include parsing such patterns in future versions.

**Comment by aki77** [comment]
Supported in v2.1.0.

https://github.com/aki77/expiring-todo-comments-action/releases/tag/v2.1.0
